complexity:
  TooManyFunctions:
    thresholdInFiles: 15
    thresholdInClasses: 15
    thresholdInInterfaces: 15
    thresholdInObjects: 15
    thresholdInEnums: 11
    ignoreDeprecated: true
    ignorePrivate: true
    ignoreOverridden: true
